### PR TITLE
Feat/make transform fns extendable

### PR DESCRIPTION
**Pull request by danielreiser**
First of all: Great work with lax.js 🎉

As I ran into the situation where I wanted my navigation to have a animatable background color opacity and couldn't find any existing transform I created my own. To keep lax updatable and prevent using my own fork I extend lax to support adding custom transform fns 😀

Hope this helps somebody else too 👍

### CODE REVIEW

**Comment by alexfoxy** [comment]
Looks good, however in this case I think for best performance you would be better off creating your background as a separate layer and then just animating the opacity?

**Comment by danielreiser** [comment]
I guess you're right, for the usecase above it might be better to introduce an additional DOM element. However I was also thinking of playing with backdrop-filter which is also net present as a transform fn 😀

**Comment by alexfoxy** [comment]
Yes makes sense. I actually re-wrote the library last weekend (lax 2.0!) which should allow for a fair bit more flexibility. Let me know if you'd like to try it out !

**Comment by danielreiser** [comment]
sure 👍

**Pull request closed without merging**
