### PR TITLE
Add support for fill-opacity attribute key

### PR DESCRIPTION
**Pull request by daltonrooney**
Support for opacity transform on SVG paths.
Ref #84

### CODE REVIEW

**Comment by alexfoxy** [comment]
Merging and testing on 1.3.0

**Comment by alexfoxy** [comment]
@daltonrooney heya, I created a 2.0 version of lax last weekend and would love to get your feedback if you had time. Check the branch out here: https://github.com/alexfoxy/laxxx/tree/version-2

Lots of new fun stuff :)

**Comment by daltonrooney** [comment]
Hey, I took a look and the new version looks _fantastic_. Moving the animations to JS is a great move, I’m really excited about that. I’m going to see if I can swap this into a project I’ve been working on and I’ll let you know how it goes.

**Comment by alexfoxy** [comment]
Awesome! If you need help just message/email me!

**Pull request merged**
