### PR TITLE
Minor code optimizations.

### PR DESCRIPTION
**Pull request by diegocr**
...as per https://github.com/alexfoxy/laxxx/pull/23#issuecomment-475869181

Please review and test carefully before merging ;)

Cheers.

### CODE REVIEW

**Comment by alexfoxy** [comment]
Nice, I'll take a look

**Comment by diegocr** [comment]
This is now facing some weird merge conflicts, if there is interest on merging this let me know it to resolve them, otherwise feel free to close it.

**Comment by alexfoxy** [comment]
Yeah, I ended up changing a bit in the latest version - sorry your merge
kinda got squashed.

Interested in merging them in if you have time to adjust tho !

**Comment by alexfoxy** [comment]
I have merged in some of your changes and made the code more consistent. Closing for now!

**Pull request closed without merging**
