### PR TITLE
docs: Add use-lax to the README.md

### PR DESCRIPTION
**Pull request by arthurdenner**
Hi! :wave: 

I found out your library yesterday and found it pretty interesting.

Following your [React example](https://codepen.io/alexfoxy/pen/PLaKaE), I created a library to abstract its use with hooks, [use-lax](https://github.com/arthurdenner/use-lax).

This PR just adds a link to my library in the README file.

### CODE REVIEW

**Comment by alexfoxy** [comment]
Interesting. Thoughts on creating a <Lax> component that would do this sort of thing?

**Comment by arthurdenner** [comment]
You can use a top level component to setup lax and a HOC on the components, like shown [here](https://codesandbox.io/s/vyr6o76yo0).

**Comment by alexfoxy** [comment]
@arthurdenner how are you getting on with this - is it working well?

**Comment by arthurdenner** [comment]
I'm not using it on a daily basis, but so far I had no complains. I think it's pretty stable and simple, I was able to recreate your first demo by just copying and pasting the HTML into a few components [here](https://039krok5ml.codesandbox.io/).

I'll try to recreate the Mario demo just to see if it works as expected too.

**Comment by arthurdenner** [comment]
@alexfoxy, here it is: https://codesandbox.io/s/r48kz0okrm.

I just copied the HTML into a component (because it's small), used `useLaxElement` on it and :tada:!

**Comment by alexfoxy** [comment]
Awesome, good job. Merged into read me 👍

**Pull request merged**
